name: Build Pelvis Engine - Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Pelvis Engine
        run: cmake --build build --config Release -j 2

      - name: Prepare release folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release

          Copy-Item `
            "build/Release/PelvisEngine.exe" `
            "release/PelvisEngine.exe"

      - name: Package Windows build
        shell: pwsh
        run: |
          Compress-Archive `
            -Path release/* `
            -DestinationPath PelvisEngine-Windows-x64.zip

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: PelvisEngine-Windows-x64
          path: PelvisEngine-Windows-x64.zip
          retention-days: 30
